# Generated by Django 3.2.9 on 2021-12-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_text', models.CharField(default='', max_length=60)),
                ('loan_date', models.CharField(default='', max_length=60)),
                ('url_image', models.CharField(default='', max_length=200)),
                ('name_user', models.CharField(default='', max_length=60)),
                ('description', models.CharField(default='', max_length=20000)),
            ],
        ),
        migrations.DeleteModel(
            name='Control',
        ),
    ]
