# Generated by Django 3.2.9 on 2021-11-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20211127_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_text',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='book',
            name='name_user',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='book',
            name='url_image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
