# Generated by Django 3.2.9 on 2021-12-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20211130_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='book',
            name='loan_date',
            field=models.CharField(default='', max_length=60),
        ),
    ]
